name: Documentation

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/documentation.yml"
      - "README.md"

jobs:
  analyze:
    name: Documentation Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.3
        with:
          fetch-depth: 0
          submodules: true

      - uses: DavidAnson/markdownlint-cli2-action@v23.2.0
        with:
          config: "code-quality-config/markdown/.markdownlint.json"
          globs: "README.md"
          separator: ","
